ztp:
  should-subscribe-to-context-component: true
quarkus:
  package:
    type: mutable-jar
  live-reload:
    password: 1234
    url: http://0.0.0.0:8080
  banner:
    path: teraflow-ztp-banner.txt
  grpc:
    server:
      port: 5050
      enable-reflection-service: true
    clients:
      context:
        host: ${quarkus.kubernetes.env.vars.context-service-host}
        port: 1010
      device:
        host: ${quarkus.kubernetes.env.vars.device-service-host}
        port: 2020
  http:
    port: 8080
  container-image:
    group: tfs
    name: controller/ztp
    registry: labs.etsi.org:5050
    tag: 0.2.0
  kubernetes:
    name: ztpservice
    image-pull-policy: Always
    labels:
      app: ztpservice
    add-version-to-label-selectors: false
    readiness-probe:
      initial-delay: 2s
      period: 10s
    liveness-probe:
      initial-delay: 2s
      period: 10s
    ports:
      http:
        host-port: 9192
        container-port: 8080
    env:
      vars:
        context-service-host: contextservice
        device-service-host: deviceservice
    resources:
      requests:
        cpu: 50m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2048Mi
