apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi-value-writerservice
  namespace: sovereign-genesis
spec:
  selector:
    matchLabels:
      app: kpi-value-writerservice
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        config.linkerd.io/skip-outbound-ports: '4222'
      labels:
        app: kpi-value-writerservice
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: INFO
        - name: PUSHGATEWAY_URL
          value: http://mon-prometheus-prometheus-pushgateway.monitoring.svc.cluster.local:9091
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        envFrom:
        - secretRef:
            name: kfk-kpi-data
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/kpi_value_writer:v3.1-customer
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 30030
        - containerPort: 9192
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats 4222; do echo
          "waiting for stateful dependencies..."; sleep 2; done;
        env:
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/busybox:v3.1-customer
        imagePullPolicy: Always
        name: init-dependencies
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kpi-value-writerservice
  name: kpi-value-writerservice
  namespace: sovereign-genesis
spec:
  ports:
  - name: grpc
    port: 30030
    protocol: TCP
    targetPort: 30030
  - name: metrics
    port: 9192
    protocol: TCP
    targetPort: 9192
  selector:
    app: kpi-value-writerservice
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kpi-value-writerservice-hpa
  namespace: sovereign-genesis
spec:
  maxReplicas: 20
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 80
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kpi-value-writerservice
