apiVersion: v1
data:
  prometheus.yml: "global:\n  scrape_interval:     15s\n  external_labels:\n    monitor:\
    \ 'teraflow-metrics'\nscrape_configs:\n- job_name: 'teraflow-metrics-pod'\n  kubernetes_sd_configs:\n\
    \  - role: pod\n    namespaces:\n      names:\n      - gitlab-ci\n- job_name:\
    \ 'teraflow-metrics-service'\n  kubernetes_sd_configs:\n  - role: service\n  \
    \  namespaces:\n      names:\n      - gitlab-ci\n- job_name: 'teraflow-metrics-endpoints'\n\
    \  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n      names:\n\
    \      - gitlab-ci\n"
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sovereign-genesis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: sovereign-genesis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      containers:
      - env:
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/prometheus:v3.1-customer
        imagePullPolicy: Always
        name: prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config-volume
          subPath: prometheus.yml
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats 4222; do echo
          "waiting for stateful dependencies..."; sleep 2; done;
        env:
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/busybox:v3.1-customer
        imagePullPolicy: Always
        name: init-dependencies
      restartPolicy: Always
      volumes:
      - configMap:
          name: prometheus-config
        name: prometheus-config-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: prometheus
  name: prometheus
  namespace: sovereign-genesis
spec:
  ports:
  - name: http
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP
--- null
...
