apiVersion: apps/v1
kind: Deployment
metadata:
  name: ztp-server-service
  namespace: sovereign-genesis
spec:
  selector:
    matchLabels:
      app: ztp-server-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ztp-server-service
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: INFO
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/ztp_server:v3.1-customer
        imagePullPolicy: Always
        name: server
        ports:
        - containerPort: 8005
        - containerPort: 5051
        - containerPort: 9192
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 250m
            memory: 128Mi
      initContainers:
      - command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats 4222; do echo
          "waiting for stateful dependencies..."; sleep 2; done;
        env:
        - name: KFK_SERVER_ADDRESS
          value: kafka-public:9092
        - name: KAFKA_SERVER
          value: kafka-public:9092
        image: us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/busybox:v3.1-customer
        imagePullPolicy: Always
        name: init-dependencies
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ztp-server-service
  name: ztp-server-service
  namespace: sovereign-genesis
spec:
  ports:
  - name: http
    port: 8005
    protocol: TCP
    targetPort: 8005
  - name: grpc
    port: 5051
    protocol: TCP
    targetPort: 5051
  - name: metrics
    port: 9192
    protocol: TCP
    targetPort: 9192
  selector:
    app: ztp-server-service
  type: ClusterIP
