# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ztp/src/main/proto/tapi_lsp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ztp/src/main/proto/tapi_lsp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!ztp/src/main/proto/tapi_lsp.proto\x12\x08tapi_lsp\"\x90\x03\n\x0eTapiLspRuleSet\x12\x11\n\tinput_sip\x18\x01 \x01(\t\x12\x12\n\noutput_sip\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\x12\n\n\x02\x62w\x18\x04 \x01(\t\x12\x13\n\x0btenant_uuid\x18\x05 \x01(\t\x12\x1b\n\x13layer_protocol_name\x18\x06 \x01(\t\x12 \n\x18layer_protocol_qualifier\x18\x07 \x01(\t\x12\x1b\n\x13lower_frequency_mhz\x18\x08 \x01(\t\x12\x1b\n\x13upper_frequency_mhz\x18\t \x01(\t\x12\x16\n\x0elink_uuid_path\x18\n \x03(\t\x12\x13\n\x0bgranularity\x18\x0b \x01(\t\x12\x11\n\tgrid_type\x18\x0c \x01(\t\x12\x11\n\tdirection\x18\r \x01(\t\x12\x15\n\rcapacity_unit\x18\x0e \x01(\t\x12\x16\n\x0e\x63\x61pacity_value\x18\x0f \x01(\t\x12 \n\x18route_objective_function\x18\x10 \x01(\t\x12\x0b\n\x03url\x18\x11 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ztp.src.main.proto.tapi_lsp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAPILSPRULESET']._serialized_start=48
  _globals['_TAPILSPRULESET']._serialized_end=448
# @@protoc_insertion_point(module_scope)
