build opticalattackdetector:
  variables:
    IMAGE_NAME: opticalattackdetector
    IMAGE_TAG: latest
  stage: build
  before_script:
  - docker image prune --force
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
  - docker buildx build -t "$IMAGE_NAME:$IMAGE_TAG" -f ./src/$IMAGE_NAME/Dockerfile
    .
  - docker tag "$IMAGE_NAME:$IMAGE_TAG" "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG"
  - docker push "$CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG"
  after_script:
  - docker image prune --force
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      == "develop" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH)
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "develop"
  - changes:
    - src/$IMAGE_NAME/**/*.{py,in,yml}
    - src/$IMAGE_NAME/Dockerfile
    - src/$IMAGE_NAME/tests/*.py
    - src/$IMAGE_NAME/tests/Dockerfile
    - manifests/${IMAGE_NAME}service.yaml
    - .gitlab-ci.yml
