# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy/src/main/proto/ipowdm.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'policy/src/main/proto/ipowdm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"policy/src/main/proto/ipowdm.proto\x12\x06ipowdm\"R\n\x0cRuleEndpoint\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\x12\x0f\n\x07ip_mask\x18\x03 \x01(\t\x12\x0f\n\x07vlan_id\x18\x04 \x01(\x05\"=\n\x13\x44igitalSubCarrierId\x12\x16\n\x0esub_carrier_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61\x63tive\x18\x02 \x01(\t\"}\n\x17\x44igitalSubCarriersGroup\x12%\n\x1d\x64igital_sub_carriers_group_id\x18\x01 \x01(\x05\x12;\n\x16\x64igital_sub_carrier_id\x18\x04 \x03(\x0b\x32\x1b.ipowdm.DigitalSubCarrierId\"\xbb\x01\n\tComponent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfrequency\x18\x02 \x01(\x02\x12\x1b\n\x13target_output_power\x18\x03 \x01(\x02\x12\x18\n\x10operational_mode\x18\x04 \x01(\x05\x12\x43\n\x1a\x64igital_sub_carriers_group\x18\x05 \x03(\x0b\x32\x1f.ipowdm.DigitalSubCarriersGroup\x12\x11\n\toperation\x18\x06 \x01(\t\"4\n\x0bTransceiver\x12%\n\ncomponents\x18\x01 \x03(\x0b\x32\x11.ipowdm.Component\"\x99\x01\n\rIpowdmRuleSet\x12!\n\x03src\x18\x01 \x03(\x0b\x32\x14.ipowdm.RuleEndpoint\x12!\n\x03\x64st\x18\x02 \x03(\x0b\x32\x14.ipowdm.RuleEndpoint\x12\n\n\x02\x62w\x18\x03 \x01(\x05\x12\x0c\n\x04uuid\x18\x04 \x01(\t\x12(\n\x0btransceiver\x18\x05 \x01(\x0b\x32\x13.ipowdm.Transceiverb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy.src.main.proto.ipowdm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RULEENDPOINT']._serialized_start=46
  _globals['_RULEENDPOINT']._serialized_end=128
  _globals['_DIGITALSUBCARRIERID']._serialized_start=130
  _globals['_DIGITALSUBCARRIERID']._serialized_end=191
  _globals['_DIGITALSUBCARRIERSGROUP']._serialized_start=193
  _globals['_DIGITALSUBCARRIERSGROUP']._serialized_end=318
  _globals['_COMPONENT']._serialized_start=321
  _globals['_COMPONENT']._serialized_end=508
  _globals['_TRANSCEIVER']._serialized_start=510
  _globals['_TRANSCEIVER']._serialized_end=562
  _globals['_IPOWDMRULESET']._serialized_start=565
  _globals['_IPOWDMRULESET']._serialized_end=718
# @@protoc_insertion_point(module_scope)
