# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: policy/src/main/proto/policy_action.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'policy/src/main/proto/policy_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)policy/src/main/proto/policy_action.proto\x12\x06policy\"w\n\x10PolicyRuleAction\x12,\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x1c.policy.PolicyRuleActionEnum\x12\x35\n\raction_config\x18\x02 \x03(\x0b\x32\x1e.policy.PolicyRuleActionConfig\"B\n\x16PolicyRuleActionConfig\x12\x12\n\naction_key\x18\x01 \x01(\t\x12\x14\n\x0c\x61\x63tion_value\x18\x02 \x01(\t*\x8e\x02\n\x14PolicyRuleActionEnum\x12\x1f\n\x1bPOLICYRULE_ACTION_NO_ACTION\x10\x00\x12\'\n#POLICYRULE_ACTION_SET_DEVICE_STATUS\x10\x01\x12,\n(POLICYRULE_ACTION_ADD_SERVICE_CONFIGRULE\x10\x02\x12,\n(POLICYRULE_ACTION_ADD_SERVICE_CONSTRAINT\x10\x03\x12\'\n#POLICY_RULE_ACTION_CALL_SERVICE_RPC\x10\x04\x12\'\n#POLICY_RULE_ACTION_RECALCULATE_PATH\x10\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'policy.src.main.proto.policy_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POLICYRULEACTIONENUM']._serialized_start=243
  _globals['_POLICYRULEACTIONENUM']._serialized_end=513
  _globals['_POLICYRULEACTION']._serialized_start=53
  _globals['_POLICYRULEACTION']._serialized_end=172
  _globals['_POLICYRULEACTIONCONFIG']._serialized_start=174
  _globals['_POLICYRULEACTIONCONFIG']._serialized_end=240
# @@protoc_insertion_point(module_scope)
