steps:
- name: gcr.io/cloud-builders/docker
  id: build-context
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/context:${_TAG}
  - -f
  - baseline/tfs-controller/src/context/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-device
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/device:${_TAG}
  - -f
  - baseline/tfs-controller/src/device/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-service
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/service:${_TAG}
  - -f
  - baseline/tfs-controller/src/service/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-pathcomp-frontend
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/pathcomp-frontend:${_TAG}
  - -f
  - baseline/tfs-controller/src/pathcomp/frontend/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-pathcomp-backend
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/pathcomp-backend:${_TAG}
  - -f
  - baseline/tfs-controller/src/pathcomp/backend/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-slice
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/slice:${_TAG}
  - -f
  - baseline/tfs-controller/src/slice/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-interdomain
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/interdomain:${_TAG}
  - -f
  - baseline/tfs-controller/src/interdomain/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-monitoring
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/monitoring:${_TAG}
  - -f
  - baseline/tfs-controller/src/monitoring/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-automation
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/automation:${_TAG}
  - -f
  - baseline/tfs-controller/src/automation/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-policy
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/policy:${_TAG}
  - -f
  - baseline/tfs-controller/src/policy/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-e2e-orchestrator
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/e2e-orchestrator:${_TAG}
  - -f
  - baseline/tfs-controller/src/e2e_orchestrator/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-vnt-manager
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/vnt-manager:${_TAG}
  - -f
  - baseline/tfs-controller/src/vnt_manager/Dockerfile
  - baseline/tfs-controller/
- name: gcr.io/cloud-builders/docker
  id: build-webui
  args:
  - build
  - -t
  - ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/webui:${_TAG}
  - -f
  - baseline/tfs-controller/src/webui/Dockerfile
  - baseline/tfs-controller/
images:
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/context:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/device:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/service:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/pathcomp-frontend:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/pathcomp-backend:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/slice:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/interdomain:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/monitoring:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/automation:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/policy:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/e2e-orchestrator:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/vnt-manager:${_TAG}
- ${_TARGET_REGION}-docker.pkg.dev/${PROJECT_ID}/sovereign-tfs/webui:${_TAG}
options:
  machineType: E2_HIGHCPU_32
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _TAG: v3.1-graduation
