steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/python-base:2026-04-20
  - -f
  - baseline/tfs-controller/src/common/Dockerfile.base
  - .
  id: build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/context:2026-04-20
  - -f
  - baseline/tfs-controller/src/context/Dockerfile
  - .
  id: build-context
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/device:2026-04-20
  - -f
  - baseline/tfs-controller/src/device/Dockerfile
  - .
  id: build-device
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/service:2026-04-20
  - -f
  - baseline/tfs-controller/src/service/Dockerfile
  - .
  id: build-service
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/slice:2026-04-20
  - -f
  - baseline/tfs-controller/src/slice/Dockerfile
  - .
  id: build-slice
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/automation:2026-04-20
  - -f
  - baseline/tfs-controller/src/automation/Dockerfile
  - .
  id: build-automation
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/monitoring:2026-04-20
  - -f
  - baseline/tfs-controller/src/monitoring/Dockerfile
  - .
  id: build-monitoring
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/nbi:2026-04-20
  - -f
  - baseline/tfs-controller/src/nbi/Dockerfile
  - .
  id: build-nbi
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/webui:2026-04-20
  - -f
  - baseline/tfs-controller/src/webui/Dockerfile
  - .
  id: build-webui
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/pathcomp:2026-04-20
  - -f
  - baseline/tfs-controller/src/pathcomp/Dockerfile
  - .
  id: build-pathcomp
  waitFor:
  - build-foundation
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - ${_CUSTOMER_REGISTRY}/policy:2026-04-20
  - -f
  - baseline/tfs-controller/src/policy/Dockerfile
  - .
  id: build-policy
  waitFor:
  - build-foundation
images:
- ${_CUSTOMER_REGISTRY}/python-base:2026-04-20
- ${_CUSTOMER_REGISTRY}/context:2026-04-20
- ${_CUSTOMER_REGISTRY}/device:2026-04-20
- ${_CUSTOMER_REGISTRY}/service:2026-04-20
- ${_CUSTOMER_REGISTRY}/slice:2026-04-20
- ${_CUSTOMER_REGISTRY}/automation:2026-04-20
- ${_CUSTOMER_REGISTRY}/monitoring:2026-04-20
- ${_CUSTOMER_REGISTRY}/nbi:2026-04-20
- ${_CUSTOMER_REGISTRY}/webui:2026-04-20
- ${_CUSTOMER_REGISTRY}/pathcomp:2026-04-20
- ${_CUSTOMER_REGISTRY}/policy:2026-04-20
options:
  machineType: E2_HIGHCPU_8
