steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials "sovereign-genesis-1776197184" --region us-central1
      echo "[DIAG] SECRET: crdb-data"
      kubectl get secret crdb-data -o json | jq -r '.data | map_values(@base64d)'
