steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      set -e
      gcloud container clusters get-credentials $_CLUSTER_NAME --region us-central1
      echo "[DIAG] DESCRIBING POD:"
      kubectl describe pod -l $_LABEL -n $_NAMESPACE
      echo "[DIAG] POD LOGS:"
      kubectl logs -l $_LABEL -n $_NAMESPACE --tail=100
