steps:
- name: gcr.io/cloud-builders/gcloud
  id: get-pat
  entrypoint: bash
  args:
  - -c
  - 'gcloud secrets versions access latest --secret="ETSI_GITLAB_PAT" > /workspace/gl_pat.txt

    '
- name: gcr.io/cloud-builders/docker
  id: auth-etsi
  entrypoint: bash
  args:
  - -c
  - 'cat /workspace/gl_pat.txt | docker login labs.etsi.org:5050 -u "sovereign-agent"
    --password-stdin

    rm /workspace/gl_pat.txt

    '
- name: gcr.io/cloud-builders/docker
  id: sync-images
  entrypoint: bash
  args:
  - -c
  - "IMAGES=(\n  \"labs.etsi.org:5050/tfs/controller/context:latest\"\n  \"labs.etsi.org:5050/tfs/controller/device:latest\"\
    \n  \"labs.etsi.org:5050/tfs/controller/service:latest\"\n  \"labs.etsi.org:5050/tfs/controller/monitoring:latest\"\
    \n  \"labs.etsi.org:5050/tfs/controller/compute:latest\"\n  \"labs.etsi.org:5050/tfs/controller/slice:latest\"\
    \n  \"labs.etsi.org:5050/tfs/controller/policy:latest\"\n  \"labs.etsi.org:5050/tfs/controller/automation:latest\"\
    \n  \"labs.etsi.org:5050/tfs/controller/pathcomp:latest\"\n  \"labs.etsi.org:5050/tfs/controller/dlt:latest\"\
    \n  \"labs.etsi.org:5050/tfs/controller/kpi_manager:latest\"\n)\n\nREGISTRY=\"\
    $_REGION-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs\"\n\nfor IMAGE in \"$${IMAGES[@]}\"\
    ; do\n  echo \"Mirroring $${IMAGE}...\"\n  TARGET=\"$${REGISTRY}/$$(basename $${IMAGE})\"\
    \n  docker pull --platform linux/amd64 $${IMAGE}\n  docker tag $${IMAGE} $${TARGET}\n\
    \  docker push $${TARGET}\ndone\n"
options:
  logging: CLOUD_LOGGING_ONLY
