stages:
- build
- unit_test
- end2end_test
include:
- local: /src/monitoring/.gitlab-ci.yml
- local: /src/nbi/.gitlab-ci.yml
- local: /src/context/.gitlab-ci.yml
- local: /src/device/.gitlab-ci.yml
- local: /src/service/.gitlab-ci.yml
- local: /src/qkd_app/.gitlab-ci.yml
- local: /src/dbscanserving/.gitlab-ci.yml
- local: /src/opticalattackmitigator/.gitlab-ci.yml
- local: /src/opticalattackdetector/.gitlab-ci.yml
- local: /src/opticalattackmanager/.gitlab-ci.yml
- local: /src/opticalcontroller/.gitlab-ci.yml
- local: /src/ztp/.gitlab-ci.yml
- local: /src/policy/.gitlab-ci.yml
- local: /src/automation/.gitlab-ci.yml
- local: /src/forecaster/.gitlab-ci.yml
- local: /src/slice/.gitlab-ci.yml
- local: /src/pathcomp/.gitlab-ci.yml
- local: /src/load_generator/.gitlab-ci.yml
- local: /src/bgpls_speaker/.gitlab-ci.yml
- local: /src/kpi_manager/.gitlab-ci.yml
- local: /src/kpi_value_api/.gitlab-ci.yml
- local: /src/analytics/.gitlab-ci.yml
- local: /src/qos_profile/.gitlab-ci.yml
- local: /src/vnt_manager/.gitlab-ci.yml
- local: /src/e2e_orchestrator/.gitlab-ci.yml
- local: /src/ztp_server/.gitlab-ci.yml
- local: /src/osm_client/.gitlab-ci.yml
- local: /src/simap_connector/.gitlab-ci.yml
- local: /src/pluggables/.gitlab-ci.yml
- local: /src/tests/.gitlab-ci.yml
