apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: questdb
spec:
  selector:
    matchLabels:
      app: questdb
  serviceName: questdb-public
  replicas: 1
  template:
    metadata:
      labels:
        app: questdb
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
      - name: metricsdb
        image: questdb/questdb:7.3.3
        ports:
        - containerPort: 9000
        - containerPort: 9009
        - containerPort: 8812
        env:
        - name: QDB_CAIRO_COMMIT_LAG
          value: '1000'
        - name: QDB_CAIRO_MAX_UNCOMMITTED_ROWS
          value: '100000'
---
apiVersion: v1
kind: Service
metadata:
  name: questdb-public
  labels:
    app: questdb
spec:
  type: ClusterIP
  selector:
    app: questdb
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
  - name: ilp
    protocol: TCP
    port: 9009
    targetPort: 9009
  - name: sql
    protocol: TCP
    port: 8812
    targetPort: 8812
