global:
  dnsService: kube-dns
  dnsNamespace: kube-system
  clusterDomain: cluster.local.
  dnsConfig: {}
mimir:
  structuredConfig:
    common:
      storage:
        backend: s3
        s3:
          endpoint: minio:9000
          access_key_id: grafana-mimir
          secret_access_key: supersecret
          insecure: true
    blocks_storage:
      s3:
        bucket_name: mimir-tsdb
    ruler_storage:
      s3:
        bucket_name: mimir-ruler
    alertmanager_storage:
      s3:
        bucket_name: mimir-alertmanager
minio:
  enabled: true
  mode: standalone
  rootUser: grafana-mimir
  rootPassword: supersecret
  buckets:
  - name: mimir-tsdb
    policy: none
    purge: false
  - name: mimir-ruler
    policy: none
    purge: false
  - name: mimir-alertmanager
    policy: none
    purge: false
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
kafka:
  enabled: false
gateway:
  enabled: true
  replicas: 1
  service:
    type: ClusterIP
    port: 80
  nginx:
    verboseLogging: true
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 500m
      memory: 512Mi
distributor:
  replicas: 0
ingester:
  replicas: 0
querier:
  replicas: 0
query_frontend:
  replicas: 0
query_scheduler:
  replicas: 0
store_gateway:
  replicas: 0
compactor:
  replicas: 0
ruler:
  enabled: false
alertmanager:
  enabled: false
overrides_exporter:
  enabled: false
memcached:
  enabled: false
memcached-queries:
  enabled: false
memcached-metadata:
  enabled: false
memcached-results:
  enabled: false
metaMonitoring:
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: false
  prometheusRule:
    enabled: false
  grafanaAgent:
    enabled: false
