alertmanager:
  enabled: false
kube-state-metrics:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: true
server:
  retention: 30d
  logLevel: debug
  resources:
    requests:
      cpu: 125m
      memory: 256Mi
    limits:
      cpu: '1'
      memory: 1Gi
  service:
    type: NodePort
    nodePort: 30090
  extraScrapeConfigs:
  - job_name: pushgateway
    static_configs:
    - targets:
      - prometheus-pushgateway.monitoring.svc.cluster.local:9091
  global:
    scrape_interval: 10s
    evaluation_interval: 10s
