# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from bgpls_speaker.service.java.netphony_topology.src.main.proto import grpcService_pb2 as bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bgpls_speaker/service/java/netphony_topology/src/main/proto/grpcService_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class updateServiceStub(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update = channel.unary_unary(
                '/src.main.proto.updateService/update',
                request_serializer=bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateRequest.SerializeToString,
                response_deserializer=bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateResponse.FromString,
                _registered_method=True)


class updateServiceServicer(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    def update(self, request, context):
        """MODIFY HERE: Update the return to streaming return.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_updateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateRequest.FromString,
                    response_serializer=bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'src.main.proto.updateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('src.main.proto.updateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class updateService(object):
    """Defining a Service, a Service can have multiple RPC operations
    """

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/src.main.proto.updateService/update',
            bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateRequest.SerializeToString,
            bgpls__speaker_dot_service_dot_java_dot_netphony__topology_dot_src_dot_main_dot_proto_dot_grpcService__pb2.updateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
