# Copyright 2022-2025 ETSI SDG TeraFlowSDN (TFS) (https://tfs.etsi.org/)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: automationservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: automationservice
  replicas: 1
  template:
    metadata:
      annotations:
        # Required for IETF L2VPN SBI when both parent and child run in same K8s cluster with Linkerd
        config.linkerd.io/skip-outbound-ports: "2002"
      labels:
        app: automationservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: 
          us-central1-docker.pkg.dev/cogctl-gke-v01/sovereign-tfs/automationservice:v3.1-graduation
        imagePullPolicy: Always
        ports:
        - containerPort: 30200
        - containerPort: 9192
        command: ["/bin/sh", "-c"]
        args:
        - "sed -i 's/wait_for_environment_variables(/if False: wait_for_environment_variables(/g'
          /var/teraflow/automation/service/__main__.py && python -m automation.service"
        env:
        - name: CONTEXT_SERVICE_HOST
          value: "contextservice"
        - name: CONTEXT_SERVICE_PORT_GRPC
          value: "1010"
        - name: DEVICE_SERVICE_HOST
          value: "deviceservice"
        - name: DEVICE_SERVICE_PORT_GRPC
          value: "2020"
        - name: KPI_MANAGER_SERVICE_HOST
          value: "127.0.0.1"
        - name: KPI_MANAGER_SERVICE_PORT_GRPC
          value: "0"
        - name: TELEMETRY_SERVICE_HOST
          value: "telemetryservice"
        - name: TELEMETRY_SERVICE_PORT_GRPC
          value: "30050"
        - name: ANALYTICS_SERVICE_HOST
          value: "analyticsservice"
        - name: ANALYTICS_SERVICE_PORT_GRPC
          value: "30080"
        - name: POLICY_SERVICE_HOST
          value: "127.0.0.1"
        - name: POLICY_SERVICE_PORT_GRPC
          value: "0"
        - name: LOG_LEVEL
          value: "INFO"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CRDB_DATABASE
          value: "tfs_automation"
        - name: CRDB_NAMESPACE
          value: "default"
        - name: CRDB_SSLMODE
          value: "disable"
        - name: CRDB_SQL_PORT
          value: "26257"
        - name: KAFKA_API_VERSION
          value: "3.7.0"
        - name: KPI_MANAGER_SERVICE_HOST
          value: "127.0.0.1"
        - name: KPI_MANAGER_SERVICE_PORT_GRPC
          value: "0"
        - name: POLICYSERVICE_SERVICE_HOST
          value: "127.0.0.1"
        - name: POLICYSERVICE_SERVICE_PORT_GRPC
          value: "0"
        envFrom:
        - secretRef:
            name: crdb-data
        startupProbe:
          grpc:
            port: 30200
          failureThreshold: 5
          periodSeconds: 1
          initialDelaySeconds: 10
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1024Mi
      initContainers:
      - name: init-dependencies
        image: busybox:1.36
        command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats-client 4222; do 
          echo "waiting for stateful dependencies..."; sleep 2; done;
---
apiVersion: v1
kind: Service
metadata:
  name: automationservice
  labels:
    app: automationservice
spec:
  type: ClusterIP
  selector:
    app: automationservice
  ports:
  - name: grpc
    protocol: TCP
    port: 30200
    targetPort: 30200
  - name: metrics
    protocol: TCP
    port: 9192
    targetPort: 9192


