apiVersion: v1
kind: Secret
metadata:
  name: crdb-data
  namespace: sovereign-genesis
type: Opaque
stringData:
  CRDB_USERNAME: admin
  CRDB_PASSWORD: quest
  CRDB_DATABASE: tfs_context
  CRDB_NAMESPACE: sovereign-genesis
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-data
  namespace: sovereign-genesis
type: Opaque
stringData:
  NATS_USERNAME: admin
  NATS_PASSWORD: quest
---
apiVersion: v1
kind: Secret
metadata:
  name: qdb-data
  namespace: sovereign-genesis
type: Opaque
stringData:
  username: admin
  password: quest
  METRICSDB_USER: admin
  METRICSDB_PASS: quest
  METRICSDB_HOSTNAME: questdb-public
---
apiVersion: v1
kind: Secret
metadata:
  name: kfk-kpi-data
  namespace: sovereign-genesis
type: Opaque
stringData:
  KFK_SERVER_ADDRESS: kafka-public.sovereign-genesis.svc.cluster.local:9092
  KAFKA_API_VERSION: 3.7.0
