apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- contextservice.yaml
- deviceservice.yaml
- serviceservice.yaml
- pathcompservice.yaml
- sliceservice.yaml
- interdomainservice.yaml
- monitoringservice.yaml
- automationservice.yaml
- policyservice.yaml
- webuiservice.yaml
images:
- name: $${_CUSTOMER_REGISTRY}/context
  newName: REGISTRY_PLACEHOLDER/context
- name: $${_CUSTOMER_REGISTRY}/device
  newName: REGISTRY_PLACEHOLDER/device
- name: $${_CUSTOMER_REGISTRY}/service
  newName: REGISTRY_PLACEHOLDER/service
- name: $${_CUSTOMER_REGISTRY}/pathcomp
  newName: REGISTRY_PLACEHOLDER/pathcomp
- name: $${_CUSTOMER_REGISTRY}/slice
  newName: REGISTRY_PLACEHOLDER/slice
- name: $${_CUSTOMER_REGISTRY}/interdomain
  newName: REGISTRY_PLACEHOLDER/interdomain
- name: $${_CUSTOMER_REGISTRY}/monitoring
  newName: REGISTRY_PLACEHOLDER/monitoring
- name: $${_CUSTOMER_REGISTRY}/automation
  newName: REGISTRY_PLACEHOLDER/automation
- name: $${_CUSTOMER_REGISTRY}/policy
  newName: REGISTRY_PLACEHOLDER/policy
- name: $${_CUSTOMER_REGISTRY}/webui
  newName: REGISTRY_PLACEHOLDER/webui
