apiVersion: apps/v1
kind: Deployment
metadata:
  name: l3-attackmitigatorservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: l3-attackmitigatorservice
  template:
    metadata:
      labels:
        app: l3-attackmitigatorservice
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: ${_CUSTOMER_REGISTRY}/l3_attackmitigator:rc13-verified
        imagePullPolicy: Always
        ports:
        - containerPort: 10002
        - containerPort: 9192
        env:
        - name: LOG_LEVEL
          value: INFO
        resources:
          requests:
            cpu: 250m
            memory: 1024Mi
          limits:
            cpu: 700m
            memory: 1024Mi
      initContainers:
      - name: init-dependencies
        image: busybox:1.36
        command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats-client 4222; do echo
          "waiting for stateful dependencies..."; sleep 2; done;
---
apiVersion: v1
kind: Service
metadata:
  name: l3-attackmitigatorservice
  labels:
    app: l3-attackmitigatorservice
spec:
  type: ClusterIP
  selector:
    app: l3-attackmitigatorservice
  ports:
  - name: metrics
    protocol: TCP
    port: 9192
    targetPort: 9192
  - name: grpc
    port: 10002
    targetPort: 10002
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: l3-attackmitigatorservice-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: l3-attackmitigatorservice
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 120
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tfs-l3-attackmitigatorservice-metric
  labels:
    app: l3-attackmitigatorservice
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: l3-attackmitigatorservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
