kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      external_labels:
        monitor: 'teraflow-metrics'
    scrape_configs:
    - job_name: 'teraflow-metrics-pod'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - gitlab-ci
    - job_name: 'teraflow-metrics-service'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - gitlab-ci
    - job_name: 'teraflow-metrics-endpoints'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - gitlab-ci
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      #serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.28.1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      restartPolicy: Always
      initContainers:
      - name: init-dependencies
        image: busybox:1.36
        command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats-client 4222; do 
          echo "waiting for stateful dependencies..."; sleep 2; done;
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
--- null
...
