kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-config
data:
  prometheus.yml: "global:\n  scrape_interval:     15s\n  external_labels:\n    monitor:\
    \ 'teraflow-metrics'\nscrape_configs:\n- job_name: 'teraflow-metrics-pod'\n  kubernetes_sd_configs:\n\
    \  - role: pod\n    namespaces:\n      names:\n      - gitlab-ci\n- job_name:\
    \ 'teraflow-metrics-service'\n  kubernetes_sd_configs:\n  - role: service\n  \
    \  namespaces:\n      names:\n      - gitlab-ci\n- job_name: 'teraflow-metrics-endpoints'\n\
    \  kubernetes_sd_configs:\n  - role: endpoints\n    namespaces:\n      names:\n\
    \      - gitlab-ci\n"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        version: v1
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.28.1
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
      restartPolicy: Always
      initContainers:
      - name: init-dependencies
        image: busybox:1.36
        command:
        - sh
        - -c
        - until nc -z cockroachdb-public 26257 && nc -z nats-client 4222; do echo
          "waiting for stateful dependencies..."; sleep 2; done;
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
  - name: http
    protocol: TCP
    port: 9090
    targetPort: 9090
