apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-contextservice-metric
  labels:
    app: contextservice
spec:
  selector:
    matchLabels:
      app: contextservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-deviceservice-metric
  labels:
    app: deviceservice
spec:
  selector:
    matchLabels:
      app: deviceservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-serviceservice-metric
  labels:
    app: serviceservice
spec:
  selector:
    matchLabels:
      app: serviceservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-sliceservice-metric
  labels:
    app: sliceservice
spec:
  selector:
    matchLabels:
      app: sliceservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-pathcompservice-metric
  labels:
    app: pathcompservice
spec:
  selector:
    matchLabels:
      app: pathcompservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-monitoringservice-metric
  labels:
    app: monitoringservice
spec:
  selector:
    matchLabels:
      app: monitoringservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-dltservice-metric
  labels:
    app: dltservice
spec:
  selector:
    matchLabels:
      app: dltservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-interdomainservice-metric
  labels:
    app: interdomainservice
spec:
  selector:
    matchLabels:
      app: interdomainservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-policyservice-metric
  labels:
    app: policyservice
spec:
  selector:
    matchLabels:
      app: policyservice
  endpoints:
  - port: metrics
    scheme: http
    path: /q/metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-ztpservice-metric
  labels:
    app: ztpservice
spec:
  selector:
    matchLabels:
      app: ztpservice
  endpoints:
  - port: metrics
    scheme: http
    path: /q/metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-nbiservice-metric
  labels:
    app: nbiservice
spec:
  selector:
    matchLabels:
      app: nbiservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-load-generatorservice-metric
  labels:
    app: load-generatorservice
spec:
  selector:
    matchLabels:
      app: load-generatorservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-dbscanservingservice-metric
  labels:
    app: dbscanservingservice
spec:
  selector:
    matchLabels:
      app: dbscanservingservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-opticalattackmitigatorservice-metric
  labels:
    app: opticalattackmitigatorservice
spec:
  selector:
    matchLabels:
      app: opticalattackmitigatorservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-opticalattackdetectorservice-metric
  labels:
    app: opticalattackdetectorservice
spec:
  selector:
    matchLabels:
      app: opticalattackdetectorservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-opticalattackmanagerservice-metric
  labels:
    app: opticalattackmanagerservice
spec:
  selector:
    matchLabels:
      app: opticalattackmanagerservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-analyticsservice-metric
  labels:
    app: analyticsservice
spec:
  selector:
    matchLabels:
      app: analyticsservice
  endpoints:
  - port: metrics-frontend
    scheme: http
    path: /metrics
    interval: 5s
  - port: metrics-backend
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-telemetryservice-metric
  labels:
    app: telemetryservice
spec:
  selector:
    matchLabels:
      app: telemetryservice
  endpoints:
  - port: metrics-frontend
    scheme: http
    path: /metrics
    interval: 5s
  - port: metrics-backend
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-kpi-managerservice-metric
  labels:
    app: kpi-managerservice
spec:
  selector:
    matchLabels:
      app: kpi-managerservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-kpi-value-apiservice-metric
  labels:
    app: kpi-value-apiservice
spec:
  selector:
    matchLabels:
      app: kpi-value-apiservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: tfs-kpi-value-writerservice-metric
  labels:
    app: kpi-value-writerservice
spec:
  selector:
    matchLabels:
      app: kpi-value-writerservice
  endpoints:
  - port: metrics
    scheme: http
    path: /metrics
    interval: 5s
  namespaceSelector:
    any: false
    matchNames:
    - tfs
