container:
  image:
    tags: 2.9-alpine
  env:
    GOMEMLIMIT: 400MiB
  merge:
    resources:
      requests:
        cpu: 1
        memory: 500Mi
      limits:
        cpu: 1
        memory: 1Gi
config:
  cluster:
    enabled: false
    replicas: 1
  jetstream:
    enabled: true
    fileStore:
      pvc:
        size: 4Gi
podTemplate:
  topologySpreadConstraints:
    kubernetes.io/hostname:
      maxSkew: 1
      whenUnsatisfiable: ScheduleAnyway
